### ISSUE TITLE
running without argument returns '0' for everything -- bit obtuse -- should prob. default to 'videoprof `pwd`'?

### ISSUE THREAD

**Issue by rudluff** [christianlent/videoprof#5]
I'm Mr. Wormhole X-treme recognizer. I am also not Mr. Man Page Reader. (Call me as smart as Col. Danning...) Spent like half an hour wondering why videoprof wouldn't detect even one TV show, and playing with all the flags like -p. :grimacing: 

Doubt defaulting to `pwd` would break anyone's workflow (any scripting would use mediainfo directly). Alternately, less end-user-friendly-simple but more in line with other command line programs that require an argument, if no non-flag arguments are passed, print a Usage message and exit immediately, instead of printing out all-0 results.

Most importantly: might help prevent obtuse bug reports in future. "It won't read anything! Everything says 0?!?! Broke my python??"

**Comment by christianlent** [comment]
Haha, good to hear from you again!

That is an excellent point! PR is in. I ended up going with your first suggestion (making PWD the default argument). You are certainly right that it's a better user experience. I will merge/publish v0.2.3 this evening.

**Comment by rudluff** [comment]
Nice!
